
# This file is automatically generated, you probably don't want to edit this

smdcorrmultiOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "smdcorrmultiOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            dottype = "ring",
            dotsize = "30",
            jitter_perc = "0",
            dotopac = "100",
            spearman = FALSE,
            upper = "data",
            lower = "neither",
            tint = FALSE,
            color1 = "gray28",
            tint2 = FALSE,
            color2 = "blue",
            lw = "25",
            fit = "line",
            smoothness = "50",
            digits = "2",
            equateaxes = FALSE,
            axesmin = "auto",
            axesmax = "auto",
            graphtitle = "auto",
            variablelabels = "auto",
            ticklabelsize = "30", ...) {

            super$initialize(
                package="showmydata",
                name="smdcorrmulti",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                takeFromDataIfMissing=TRUE,
                suggested=list(
                    "ordinal",
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..dottype <- jmvcore::OptionList$new(
                "dottype",
                dottype,
                options=list(
                    "ring",
                    "dot"),
                default="ring")
            private$..dotsize <- jmvcore::OptionString$new(
                "dotsize",
                dotsize,
                default="30")
            private$..jitter_perc <- jmvcore::OptionString$new(
                "jitter_perc",
                jitter_perc,
                default="0")
            private$..dotopac <- jmvcore::OptionString$new(
                "dotopac",
                dotopac,
                default="100")
            private$..spearman <- jmvcore::OptionBool$new(
                "spearman",
                spearman,
                default=FALSE)
            private$..upper <- jmvcore::OptionList$new(
                "upper",
                upper,
                options=list(
                    "stats",
                    "data",
                    "neither"),
                default="data")
            private$..lower <- jmvcore::OptionList$new(
                "lower",
                lower,
                options=list(
                    "stats",
                    "data",
                    "neither"),
                default="neither")
            private$..tint <- jmvcore::OptionBool$new(
                "tint",
                tint,
                default=FALSE)
            private$..color1 <- jmvcore::OptionString$new(
                "color1",
                color1,
                default="gray28")
            private$..tint2 <- jmvcore::OptionBool$new(
                "tint2",
                tint2,
                default=FALSE)
            private$..color2 <- jmvcore::OptionString$new(
                "color2",
                color2,
                default="blue")
            private$..lw <- jmvcore::OptionString$new(
                "lw",
                lw,
                default="25")
            private$..fit <- jmvcore::OptionList$new(
                "fit",
                fit,
                options=list(
                    "none",
                    "line",
                    "curve",
                    "both"),
                default="line")
            private$..smoothness <- jmvcore::OptionString$new(
                "smoothness",
                smoothness,
                default="50")
            private$..digits <- jmvcore::OptionList$new(
                "digits",
                digits,
                options=list(
                    "2",
                    "3",
                    "4",
                    "5"),
                default="2")
            private$..equateaxes <- jmvcore::OptionBool$new(
                "equateaxes",
                equateaxes,
                default=FALSE)
            private$..axesmin <- jmvcore::OptionString$new(
                "axesmin",
                axesmin,
                default="auto")
            private$..axesmax <- jmvcore::OptionString$new(
                "axesmax",
                axesmax,
                default="auto")
            private$..graphtitle <- jmvcore::OptionString$new(
                "graphtitle",
                graphtitle,
                default="auto")
            private$..variablelabels <- jmvcore::OptionString$new(
                "variablelabels",
                variablelabels,
                default="auto")
            private$..ticklabelsize <- jmvcore::OptionString$new(
                "ticklabelsize",
                ticklabelsize,
                default="30")

            self$.addOption(private$..vars)
            self$.addOption(private$..dottype)
            self$.addOption(private$..dotsize)
            self$.addOption(private$..jitter_perc)
            self$.addOption(private$..dotopac)
            self$.addOption(private$..spearman)
            self$.addOption(private$..upper)
            self$.addOption(private$..lower)
            self$.addOption(private$..tint)
            self$.addOption(private$..color1)
            self$.addOption(private$..tint2)
            self$.addOption(private$..color2)
            self$.addOption(private$..lw)
            self$.addOption(private$..fit)
            self$.addOption(private$..smoothness)
            self$.addOption(private$..digits)
            self$.addOption(private$..equateaxes)
            self$.addOption(private$..axesmin)
            self$.addOption(private$..axesmax)
            self$.addOption(private$..graphtitle)
            self$.addOption(private$..variablelabels)
            self$.addOption(private$..ticklabelsize)
        }),
    active = list(
        vars = function() private$..vars$value,
        dottype = function() private$..dottype$value,
        dotsize = function() private$..dotsize$value,
        jitter_perc = function() private$..jitter_perc$value,
        dotopac = function() private$..dotopac$value,
        spearman = function() private$..spearman$value,
        upper = function() private$..upper$value,
        lower = function() private$..lower$value,
        tint = function() private$..tint$value,
        color1 = function() private$..color1$value,
        tint2 = function() private$..tint2$value,
        color2 = function() private$..color2$value,
        lw = function() private$..lw$value,
        fit = function() private$..fit$value,
        smoothness = function() private$..smoothness$value,
        digits = function() private$..digits$value,
        equateaxes = function() private$..equateaxes$value,
        axesmin = function() private$..axesmin$value,
        axesmax = function() private$..axesmax$value,
        graphtitle = function() private$..graphtitle$value,
        variablelabels = function() private$..variablelabels$value,
        ticklabelsize = function() private$..ticklabelsize$value),
    private = list(
        ..vars = NA,
        ..dottype = NA,
        ..dotsize = NA,
        ..jitter_perc = NA,
        ..dotopac = NA,
        ..spearman = NA,
        ..upper = NA,
        ..lower = NA,
        ..tint = NA,
        ..color1 = NA,
        ..tint2 = NA,
        ..color2 = NA,
        ..lw = NA,
        ..fit = NA,
        ..smoothness = NA,
        ..digits = NA,
        ..equateaxes = NA,
        ..axesmin = NA,
        ..axesmax = NA,
        ..graphtitle = NA,
        ..variablelabels = NA,
        ..ticklabelsize = NA)
)

smdcorrmultiResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "smdcorrmultiResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correlation for multiple measures")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Plot",
                width=700,
                height=700,
                renderFun=".plot"))}))

smdcorrmultiBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "smdcorrmultiBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "showmydata",
                name = "smdcorrmulti",
                version = c(1,0,0),
                options = options,
                results = smdcorrmultiResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE)
        }))

#' Correlation for multiple measures
#'
#' This is the description of the Correlation for multiple measures app.
#' 
#' This is the description of the Correlation for multiple measures app.
#' 
#' This is the description of the Correlation for multiple measures app.
#' 
#' @param data .
#' @param vars .
#' @param dottype .
#' @param dotsize .
#' @param jitter_perc .
#' @param dotopac .
#' @param spearman .
#' @param upper .
#' @param lower .
#' @param tint .
#' @param color1 .
#' @param tint2 .
#' @param color2 .
#' @param lw .
#' @param fit .
#' @param smoothness .
#' @param digits .
#' @param equateaxes .
#' @param axesmin .
#' @param axesmax .
#' @param graphtitle .
#' @param variablelabels .
#' @param ticklabelsize .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
smdcorrmulti <- function(
    data,
    vars,
    dottype = "ring",
    dotsize = "30",
    jitter_perc = "0",
    dotopac = "100",
    spearman = FALSE,
    upper = "data",
    lower = "neither",
    tint = FALSE,
    color1 = "gray28",
    tint2 = FALSE,
    color2 = "blue",
    lw = "25",
    fit = "line",
    smoothness = "50",
    digits = "2",
    equateaxes = FALSE,
    axesmin = "auto",
    axesmax = "auto",
    graphtitle = "auto",
    variablelabels = "auto",
    ticklabelsize = "30") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("smdcorrmulti requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))

    vars <- `if`( ! missing(vars), vars, colnames(data))

    options <- smdcorrmultiOptions$new(
        vars = vars,
        dottype = dottype,
        dotsize = dotsize,
        jitter_perc = jitter_perc,
        dotopac = dotopac,
        spearman = spearman,
        upper = upper,
        lower = lower,
        tint = tint,
        color1 = color1,
        tint2 = tint2,
        color2 = color2,
        lw = lw,
        fit = fit,
        smoothness = smoothness,
        digits = digits,
        equateaxes = equateaxes,
        axesmin = axesmin,
        axesmax = axesmax,
        graphtitle = graphtitle,
        variablelabels = variablelabels,
        ticklabelsize = ticklabelsize)

    analysis <- smdcorrmultiClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

