
# This file is automatically generated, you probably don't want to edit this

smdcorr2Options <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "smdcorr2Options",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            ind = NULL,
            dottype = "ring",
            color_dot = "black",
            dotsize = "30",
            xjitter = "0",
            yjitter = "0",
            dotopac = "100",
            spearman = FALSE,
            lw = "40",
            showresiduals = FALSE,
            lsline = TRUE,
            color1 = "black",
            polynomial = FALSE,
            color2 = "blue",
            polynomial_degree = "2",
            spline = FALSE,
            color3 = "red",
            spline_smoothness = "50",
            rug = FALSE,
            xmin = "auto",
            xmax = "auto",
            ymin = "auto",
            ymax = "auto",
            showstats = TRUE,
            graphtitle = "auto",
            xvariablelabel = "auto",
            yvariablelabel = "auto", ...) {

            super$initialize(
                package="showmydata",
                name="smdcorr2",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..ind <- jmvcore::OptionVariable$new(
                "ind",
                ind)
            private$..dottype <- jmvcore::OptionList$new(
                "dottype",
                dottype,
                options=list(
                    "ring",
                    "dot"),
                default="ring")
            private$..color_dot <- jmvcore::OptionString$new(
                "color_dot",
                color_dot,
                default="black")
            private$..dotsize <- jmvcore::OptionString$new(
                "dotsize",
                dotsize,
                default="30")
            private$..xjitter <- jmvcore::OptionString$new(
                "xjitter",
                xjitter,
                default="0")
            private$..yjitter <- jmvcore::OptionString$new(
                "yjitter",
                yjitter,
                default="0")
            private$..dotopac <- jmvcore::OptionString$new(
                "dotopac",
                dotopac,
                default="100")
            private$..spearman <- jmvcore::OptionBool$new(
                "spearman",
                spearman,
                default=FALSE)
            private$..lw <- jmvcore::OptionString$new(
                "lw",
                lw,
                default="40")
            private$..showresiduals <- jmvcore::OptionBool$new(
                "showresiduals",
                showresiduals,
                default=FALSE)
            private$..lsline <- jmvcore::OptionBool$new(
                "lsline",
                lsline,
                default=TRUE)
            private$..color1 <- jmvcore::OptionString$new(
                "color1",
                color1,
                default="black")
            private$..polynomial <- jmvcore::OptionBool$new(
                "polynomial",
                polynomial,
                default=FALSE)
            private$..color2 <- jmvcore::OptionString$new(
                "color2",
                color2,
                default="blue")
            private$..polynomial_degree <- jmvcore::OptionList$new(
                "polynomial_degree",
                polynomial_degree,
                options=list(
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7"),
                default="2")
            private$..spline <- jmvcore::OptionBool$new(
                "spline",
                spline,
                default=FALSE)
            private$..color3 <- jmvcore::OptionString$new(
                "color3",
                color3,
                default="red")
            private$..spline_smoothness <- jmvcore::OptionString$new(
                "spline_smoothness",
                spline_smoothness,
                default="50")
            private$..rug <- jmvcore::OptionBool$new(
                "rug",
                rug,
                default=FALSE)
            private$..xmin <- jmvcore::OptionString$new(
                "xmin",
                xmin,
                default="auto")
            private$..xmax <- jmvcore::OptionString$new(
                "xmax",
                xmax,
                default="auto")
            private$..ymin <- jmvcore::OptionString$new(
                "ymin",
                ymin,
                default="auto")
            private$..ymax <- jmvcore::OptionString$new(
                "ymax",
                ymax,
                default="auto")
            private$..showstats <- jmvcore::OptionBool$new(
                "showstats",
                showstats,
                default=TRUE)
            private$..graphtitle <- jmvcore::OptionString$new(
                "graphtitle",
                graphtitle,
                default="auto")
            private$..xvariablelabel <- jmvcore::OptionString$new(
                "xvariablelabel",
                xvariablelabel,
                default="auto")
            private$..yvariablelabel <- jmvcore::OptionString$new(
                "yvariablelabel",
                yvariablelabel,
                default="auto")

            self$.addOption(private$..dep)
            self$.addOption(private$..ind)
            self$.addOption(private$..dottype)
            self$.addOption(private$..color_dot)
            self$.addOption(private$..dotsize)
            self$.addOption(private$..xjitter)
            self$.addOption(private$..yjitter)
            self$.addOption(private$..dotopac)
            self$.addOption(private$..spearman)
            self$.addOption(private$..lw)
            self$.addOption(private$..showresiduals)
            self$.addOption(private$..lsline)
            self$.addOption(private$..color1)
            self$.addOption(private$..polynomial)
            self$.addOption(private$..color2)
            self$.addOption(private$..polynomial_degree)
            self$.addOption(private$..spline)
            self$.addOption(private$..color3)
            self$.addOption(private$..spline_smoothness)
            self$.addOption(private$..rug)
            self$.addOption(private$..xmin)
            self$.addOption(private$..xmax)
            self$.addOption(private$..ymin)
            self$.addOption(private$..ymax)
            self$.addOption(private$..showstats)
            self$.addOption(private$..graphtitle)
            self$.addOption(private$..xvariablelabel)
            self$.addOption(private$..yvariablelabel)
        }),
    active = list(
        dep = function() private$..dep$value,
        ind = function() private$..ind$value,
        dottype = function() private$..dottype$value,
        color_dot = function() private$..color_dot$value,
        dotsize = function() private$..dotsize$value,
        xjitter = function() private$..xjitter$value,
        yjitter = function() private$..yjitter$value,
        dotopac = function() private$..dotopac$value,
        spearman = function() private$..spearman$value,
        lw = function() private$..lw$value,
        showresiduals = function() private$..showresiduals$value,
        lsline = function() private$..lsline$value,
        color1 = function() private$..color1$value,
        polynomial = function() private$..polynomial$value,
        color2 = function() private$..color2$value,
        polynomial_degree = function() private$..polynomial_degree$value,
        spline = function() private$..spline$value,
        color3 = function() private$..color3$value,
        spline_smoothness = function() private$..spline_smoothness$value,
        rug = function() private$..rug$value,
        xmin = function() private$..xmin$value,
        xmax = function() private$..xmax$value,
        ymin = function() private$..ymin$value,
        ymax = function() private$..ymax$value,
        showstats = function() private$..showstats$value,
        graphtitle = function() private$..graphtitle$value,
        xvariablelabel = function() private$..xvariablelabel$value,
        yvariablelabel = function() private$..yvariablelabel$value),
    private = list(
        ..dep = NA,
        ..ind = NA,
        ..dottype = NA,
        ..color_dot = NA,
        ..dotsize = NA,
        ..xjitter = NA,
        ..yjitter = NA,
        ..dotopac = NA,
        ..spearman = NA,
        ..lw = NA,
        ..showresiduals = NA,
        ..lsline = NA,
        ..color1 = NA,
        ..polynomial = NA,
        ..color2 = NA,
        ..polynomial_degree = NA,
        ..spline = NA,
        ..color3 = NA,
        ..spline_smoothness = NA,
        ..rug = NA,
        ..xmin = NA,
        ..xmax = NA,
        ..ymin = NA,
        ..ymax = NA,
        ..showstats = NA,
        ..graphtitle = NA,
        ..xvariablelabel = NA,
        ..yvariablelabel = NA)
)

smdcorr2Results <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "smdcorr2Results",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correlation for 2 measures")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Plot",
                width=600,
                height=600,
                renderFun=".plot"))}))

smdcorr2Base <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "smdcorr2Base",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "showmydata",
                name = "smdcorr2",
                version = c(1,0,0),
                options = options,
                results = smdcorr2Results$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE)
        }))

#' Correlation for 2 measures
#'
#' This is the description of the Correlation for 2 measures app.
#' 
#' This is the description of the Correlation for 2 measures app.
#' 
#' This is the description of the Correlation for 2 measures app.
#' 
#' @param data .
#' @param dep .
#' @param ind .
#' @param dottype .
#' @param color_dot .
#' @param dotsize .
#' @param xjitter .
#' @param yjitter .
#' @param dotopac .
#' @param spearman .
#' @param lw .
#' @param showresiduals .
#' @param lsline .
#' @param color1 .
#' @param polynomial .
#' @param color2 .
#' @param polynomial_degree .
#' @param spline .
#' @param color3 .
#' @param spline_smoothness .
#' @param rug .
#' @param xmin .
#' @param xmax .
#' @param ymin .
#' @param ymax .
#' @param showstats .
#' @param graphtitle .
#' @param xvariablelabel .
#' @param yvariablelabel .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
smdcorr2 <- function(
    data,
    dep,
    ind,
    dottype = "ring",
    color_dot = "black",
    dotsize = "30",
    xjitter = "0",
    yjitter = "0",
    dotopac = "100",
    spearman = FALSE,
    lw = "40",
    showresiduals = FALSE,
    lsline = TRUE,
    color1 = "black",
    polynomial = FALSE,
    color2 = "blue",
    polynomial_degree = "2",
    spline = FALSE,
    color3 = "red",
    spline_smoothness = "50",
    rug = FALSE,
    xmin = "auto",
    xmax = "auto",
    ymin = "auto",
    ymax = "auto",
    showstats = TRUE,
    graphtitle = "auto",
    xvariablelabel = "auto",
    yvariablelabel = "auto") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("smdcorr2 requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(ind)) ind <- jmvcore::resolveQuo(jmvcore::enquo(ind))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(ind), ind, NULL))


    options <- smdcorr2Options$new(
        dep = dep,
        ind = ind,
        dottype = dottype,
        color_dot = color_dot,
        dotsize = dotsize,
        xjitter = xjitter,
        yjitter = yjitter,
        dotopac = dotopac,
        spearman = spearman,
        lw = lw,
        showresiduals = showresiduals,
        lsline = lsline,
        color1 = color1,
        polynomial = polynomial,
        color2 = color2,
        polynomial_degree = polynomial_degree,
        spline = spline,
        color3 = color3,
        spline_smoothness = spline_smoothness,
        rug = rug,
        xmin = xmin,
        xmax = xmax,
        ymin = ymin,
        ymax = ymax,
        showstats = showstats,
        graphtitle = graphtitle,
        xvariablelabel = xvariablelabel,
        yvariablelabel = yvariablelabel)

    analysis <- smdcorr2Class$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

